### ISSUE TITLE
rename repo to match name in docker hub

### ISSUE THREAD

**Issue by guruofgentoo** [level12/python-test-multi#8]
https://github.com/level12/board-devops/issues/29

**Comment by n8harmon** [comment]
- Found this issue helpful: https://github.com/docker/hub-feedback/issues/313
  - Updated automated build to happen through https://cloud.docker.com using [these instructions](https://github.com/docker/hub-feedback/issues/313#issuecomment-265843090)
  - Some metadata did not get updated on Docker hub similar to [this note](https://github.com/docker/hub-feedback/issues/313#issuecomment-317333185)
- Added a Slack notification to the `#builds` channel, so that we will be notified each time an automated build completes regardless of whether it succeeds or fails.
